# Generated by Django 5.1.3 on 2024-12-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experiencia_necesaria',
            field=models.IntegerField(default=100),
        ),
    ]
