# Generated by Django 5.1.3 on 2024-12-11 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_character_experiencia_necesaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('recompensa_experiencia', models.IntegerField()),
                ('recompensa_oro', models.IntegerField()),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MisionActiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progreso', models.IntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.mision')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
